language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - python setup.py -q install
  - pip install blinker nose coverage coveralls
# command to run tests
script: coverage run `which nosetests`
after_success:
  - coveralls
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
